---
# Basic Ubuntu setup such as:
# - Set Hostname
# - Disable Password Login
# - Disable Root Login
# - Enable sudo for user with no password
# - Resize disk (where applicable)

- hosts: ubuntu_servers
  roles:
  - role: setup
