---
# Setup scripts

- name: Create required directories
  file:
    path: "{{ item }}"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    state: directory
    mode: 0755
  loop:
    - "{{ minecraft_base_dir }}"
    - "{{ minecraft_server_dir }}"
  become: yes

- name: Create Minecraft server files
  template:
    src: "{{ item }}.j2"
    dest: "{{ minecraft_server_dir }}/{{ item }}"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: 0664
  loop:
    - server.properties

- name: Place eula file
  copy: 
    src: "eula.txt"
    dest: "{{ minecraft_server_dir }}/eula.txt"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: 0664

- name: Copy shell scripts to directory
  copy: 
    src: "{{ item }}"
    dest: "{{ minecraft_server_dir }}/{{ item }}"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: 0774
  loop:
    - start.sh
    - stop.sh

- name: Obtain latest MC version
  shell:
    cmd: curl -s https://launchermeta.mojang.com/mc/game/version_manifest.json | python3 -c "import sys, json; print(json.load(sys.stdin)['latest']['release'])"
    chdir: "{{ minecraft_server_dir }}"
  register: curl_output
  when: minecraft_version is undefined

- name: Set minecraft_version to latest if not already defined
  set_fact:
    minecraft_version: "{{ curl_output.stdout }}"
  when: minecraft_version is undefined

- name: Get server jar download URL
  shell:
    cmd: curl https://mcversions.net/download/{{ minecraft_version }} --silent | grep "server.jar" | sed 's/.*\(https:\/\/.*server.jar\).*/\1/g'
  register: get_download_curl

- name: Print download url
  debug:
    msg: "Download url: {{ get_download_curl.stdout }}"

# - name: Download server jar
#   shell:
#     cmd: wget 

  

- name: Copy systemd file for the minecraft service
  template:
    src: "{{ item }}.j2"
    dest: '/usr/lib/systemd/system/{{ item }}'
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: 0664
  loop:
    - minecraft.service
  become: yes

- name: Daemon-reload
  systemd:
    name: 'minecraft'
    daemon_reload: yes
    enabled: yes
  become: yes

# - name: Enable Minecraft Service
#   systemd:
#   become: yes


