---
# Setup scripts

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "{{ minecraft_base_dir }}"
    - "{{ minecraft_scripts_dir }}"
 
- name: Copy shell scripts to directory
  copy: 
    src: "{{ item }}"
    dest: "{{ minecraft_scripts_dir }}"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: 0774
  loop:
    - start.sh
    - stop.sh
    - install.sh

- name: Copy systemd file for the minecraft service
  copy:
    src: minecraft.service
    dest: '/usr/lib/systemd/system/minecraft.service'
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: 0664

- name: Daemon-reload
  systemd:
    daemon_reload: yes

- name: Enable Minecraft Service
  systemd:
    enabled: yes


