---
# Setup scripts

- name: Create required directories
  file:
    path: "{{ item }}"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    state: directory
    mode: 0755
  loop:
    - "{{ minecraft_base_dir }}"
    - "{{ minecraft_server_dir }}"
  become: yes

- name: Create Minecraft server files
  template:
    src: "{{ item }}.j2"
    dest: "{{ minecraft_server_dir }}/{{ item }}"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: 0664
  loop:
    - server.properties

- name: Place eula file
  copy: 
    src: "eula.txt"
    dest: "{{ minecraft_server_dir }}/eula.txt"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: 0664

- name: Copy shell scripts to directory
  copy: 
    src: "{{ item }}"
    dest: "{{ minecraft_server_dir }}/{{ item }}"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: 0774
  loop:
    - start.sh
    - stop.sh

- name: Copy systemd file for the minecraft service
  template:
    src: "{{ item }}"
    dest: '/usr/lib/systemd/system/{{ item }}'
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: 0664
  loop:
    - minecraft.service

- name: Daemon-reload
  systemd:
    daemon_reload: yes

- name: Enable Minecraft Service
  systemd:
    enabled: yes


